spring.datasource.url=jdbc:postgresql://localhost:5432/digitalLocker
spring.datasource.username=postgres
spring.datasource.password=Tomar@tomar1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=my-super-secret-key-for-learning-project
jwt.expiration=86400000